# Generated by Django 4.2.4 on 2023-08-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='car',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.carmodel'),
        ),
    ]
