# Generated by Django 4.2.4 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='car',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
