# Generated by Django 4.2.4 on 2023-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_topsells'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topsells',
            options={'verbose_name': 'Topsell', 'verbose_name_plural': 'Topsells'},
        ),
        migrations.AddField(
            model_name='products',
            name='first_li',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='second_li',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='third_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
