# Generated by Django 4.2.4 on 2023-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_topsells_options_products_first_li_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='first_li',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_li',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_number',
        ),
        migrations.AddField(
            model_name='products',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
