# Generated by Django 4.2.4 on 2023-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='headlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('exiting', models.BooleanField(default=True)),
                ('car', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'headlight',
                'verbose_name_plural': 'headlights',
            },
        ),
        migrations.CreateModel(
            name='lent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('exiting', models.BooleanField(default=True)),
                ('car', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'lent',
                'verbose_name_plural': 'lents',
            },
        ),
        migrations.CreateModel(
            name='radiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('exiting', models.BooleanField(default=True)),
                ('car', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'radiator',
                'verbose_name_plural': 'radiators',
            },
        ),
        migrations.CreateModel(
            name='Separ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('exiting', models.BooleanField(default=True)),
                ('car', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'separ',
                'verbose_name_plural': 'separs',
            },
        ),
    ]
