# Generated by Django 4.2.4 on 2023-08-30 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_headlight_lent_radiator_separ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('exiting', models.BooleanField(default=True)),
                ('car', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'mainproduct',
                'verbose_name_plural': 'mainproducts',
            },
        ),
        migrations.RenameField(
            model_name='topsells',
            old_name='topsellproductitle',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('paymentmethod', models.CharField(blank=True, max_length=200)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdPay',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transId', models.CharField(max_length=100, unique=True)),
                ('lastStatus', models.IntegerField(blank=True, null=True)),
                ('trackIdpay', models.IntegerField(blank=True, null=True)),
                ('trackShaparak', models.CharField(blank=True, max_length=50, null=True)),
                ('amountCreate', models.IntegerField(blank=True, null=True)),
                ('amountPaid', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('dateShaparak', models.DateTimeField(blank=True, null=True)),
                ('dateVerify', models.DateTimeField(blank=True, null=True)),
                ('cardNo', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
