# Generated by Django 4.2.4 on 2023-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_mainproduct_rename_topsellproductitle_topsells_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shippingaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('nocode', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('capital', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='headlight',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='headlight',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lent',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='lent',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='radiator',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='separ',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='separ',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='topsells',
            name='brand',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='topsells',
            name='logoimage',
            field=models.URLField(blank=True),
        ),
    ]
