# Generated by Django 4.2.4 on 2023-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
