# Generated by Django 4.2.4 on 2023-08-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
