# Generated by Django 4.2.4 on 2023-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_shippingaddress_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlight',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lent',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='radiator',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='separ',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='topsells',
            name='productid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
