# Generated by Django 4.2.4 on 2023-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_products_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
